export const cuisineList  = [
  "T-Shirts",
  "Hoodies",
  "Tank Tops",
  "Long-Sleeve Shirts",
  "Sweatshirts",
  "Polo Shirts",
  "Kidswear",
  "Accessories",
  "Graphic Tees",
  "Custom Designs",
  "Eco-Friendly Apparel",
  "Sportswear",
  "Workwear",
  "Party Wear",
  "Summer Collection",
  "Winter Collection",
  "Unisex Clothing",
  "Casual Wear",
  "Premium Fabrics",
  "Limited Edition",
  "Vintage Styles",
  "Streetwear",
  "Activewear",
  "Formal Wear",
  "Themed Apparel",
];
